version: '3.1'

services:
  springboot:
    build: .
    container_name: planetapi-app
    environment:
      - MONGO_HOST=planetapi-mongo
      - MONGO_PORT=27017
      - MONGO_DATABASE=planetsdb
    ports:
      - 8888:8888
    working_dir: /app
    depends_on:
      - mongo
    networks:
      - planetapi-mongo
    restart: always

  mongo:
    image: mongo
    container_name: planetapi-mongo
    networks:
      - planetapi-mongo
    volumes:
      - $HOME/data/springboot-mongo-data:/data/db
      - $HOME/data/springboot-mongo-bkp:/data/bkp
    restart: always

networks:
  planetapi-mongo:
    driver: bridge